create type verification_status as enum ('not_found_yet','unverified','verified','needs_review','broken_source');
create table districts (id uuid primary key default gen_random_uuid(), name text not null, county text not null, state text not null check (state in ('ID','OR')), superintendent text, office_address text, phone text, website text, cte_director text, source_url text, date_verified date, created_at timestamptz default now());
create table schools (id uuid primary key default gen_random_uuid(), name text not null, district_id uuid references districts(id), county text not null, state text not null check (state in ('ID','OR')), grades_served text, school_type text, address text, phone text, website text, latitude numeric, longitude numeric, nces_id text, source_url text, date_imported date default current_date, date_verified date, verification_status verification_status default 'unverified', created_at timestamptz default now());
create table programs (id uuid primary key default gen_random_uuid(), school_id uuid references schools(id) on delete cascade, name text not null, program_area text, source_url text, date_verified date, verification_status verification_status default 'unverified');
create table contacts (id uuid primary key default gen_random_uuid(), name text, title text, email text, phone text, extension text, school_id uuid references schools(id) on delete set null, district_id uuid references districts(id) on delete set null, program_area text, source_url text not null, source_page_title text, date_verified date not null default current_date, confidence_score text check (confidence_score in ('high','medium','low')), extraction_notes text, verification_status verification_status default 'unverified');
create table source_urls (id uuid primary key default gen_random_uuid(), school_id uuid references schools(id), district_id uuid references districts(id), url text not null unique, page_title text, last_crawled_at timestamptz, http_status int, is_official boolean default true, notes text);
create table crawl_runs (id uuid primary key default gen_random_uuid(), started_at timestamptz default now(), completed_at timestamptz, run_type text not null, status text not null default 'running', pages_checked int default 0, contacts_found int default 0, errors jsonb default '[]');
create table recruiting_notes (id uuid primary key default gen_random_uuid(), school_id uuid references schools(id), district_id uuid references districts(id), contact_id uuid references contacts(id), note text, last_visit date, next_visit date, relationship_status text, recruiting_priority text, contact_history text, follow_up_date date, updated_at timestamptz default now());
alter table districts enable row level security; alter table schools enable row level security; alter table contacts enable row level security; alter table programs enable row level security; alter table source_urls enable row level security; alter table crawl_runs enable row level security; alter table recruiting_notes enable row level security;
