'use client';

import { useEffect, useState } from 'react';
import HelpIcon from '@/components/HelpIcon';
const actions = [['Discover schools and districts','/api/admin/discover/start-schools'],['Discover school websites','/api/admin/discover/start-websites'],['Discover contacts','/api/admin/discover/start-contacts'],['Run next crawl batch','/api/admin/discover/run-batch']] as const;
function Stat({label,value}:{label:string;value:unknown}){return <div className="rounded-xl border border-slate-800 bg-slate-950/70 p-4"><div className="text-2xl font-bold">{String(value ?? 0)}</div><div className="text-sm text-slate-400">{label}</div></div>}
export default function DiscoverPage(){const[status,setStatus]=useState<Record<string,any>|null>(null);const[result,setResult]=useState<Record<string,unknown>|null>(null);const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState<string|null>(null);async function refresh(){const r=await fetch('/api/admin/discover/status');const b=await r.json();if(r.ok)setStatus(b)}useEffect(()=>{refresh().catch(()=>undefined)},[]);async function run(label:string,url:string){setLoading(label);setError(null);try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({limit:5})});const b=await r.json();if(!r.ok)throw new Error(b.error??'Discovery action failed');setResult(b);await refresh()}catch(e){setError(e instanceof Error?e.message:'Discovery action failed')}finally{setLoading(null)}}const by=status?.queue?.byStatus??{};const last=status?.lastRun;
return <main className="mx-auto max-w-6xl space-y-6 p-6"><div><p className="text-sm uppercase tracking-[.25em] text-sky-300">Human-guided crawl workflow</p><h1 className="mt-2 text-3xl font-bold">Discover schools, websites, and contacts <HelpIcon topic="How to use Discovery"/></h1><p className="mt-2 text-slate-400">Use these controls to seed expected coverage, queue official pages, and process crawl work in safe web-app-sized batches.</p></div>
<section className="rounded-2xl border border-sky-900/60 bg-slate-900 p-6 shadow-xl shadow-slate-950/30"><h2 className="text-xl font-semibold">How to use discovery</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><div><h3 className="font-semibold text-sky-200">Discover schools and districts</h3><p className="text-sm text-slate-400">Seeds or verifies the approved territory baseline so expected schools and districts exist in the system.</p></div><div><h3 className="font-semibold text-sky-200">Discover school websites</h3><p className="text-sm text-slate-400">Finds or verifies official school and district website pages and adds relevant website targets to the crawl queue.</p></div><div><h3 className="font-semibold text-sky-200">Discover contacts</h3><p className="text-sm text-slate-400">Queues staff/contact discovery from official pages for principals, counselors, CTE, shop, and similar roles.</p></div><div><h3 className="font-semibold text-sky-200">Run next crawl batch</h3><p className="text-sm text-slate-400">Processes a limited number of queued tasks. Batches are intentionally small for Vercel and each run may verify pages or queue more work.</p></div></div><div className="mt-5 rounded-xl border border-slate-800 bg-slate-950 p-4 text-sm text-slate-300"><b>Run multiple batches</b> because one batch does not finish the territory; processed pages can add more crawl targets. <b>Stop</b> when pending reaches 0, several runs produce no meaningful changes, results are only already-known pages, or remaining work is no longer improving contact coverage and needs manual review. Success means populated school/district counts, better website coverage, emerging contacts, and smaller clearer missing-data gaps.</div></section>
<section className="grid gap-4 md:grid-cols-4"><Stat label="Pending" value={by.pending}/><Stat label="Complete" value={by.complete}/><Stat label="Failed" value={by.failed}/><Stat label="Most recent batch" value={last ? `${last.run_type} · ${last.status}` : 'None yet'}/></section>
<div className="flex flex-wrap gap-3">{actions.map(([label,url])=><button key={url} onClick={()=>run(label,url)} disabled={!!loading} className="rounded-xl bg-sky-400 px-4 py-2 font-semibold text-slate-950 disabled:opacity-60">{loading===label?'Running…':label}</button>)}<button onClick={refresh} className="rounded-xl border border-slate-700 px-4 py-2">Refresh status</button></div>{error?<pre className="rounded-xl border border-red-800 bg-red-950 p-4 text-red-100">{error}</pre>:null}
<section className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 className="mb-2 font-semibold">Most recent result</h2><pre className="max-h-96 overflow-auto text-xs text-slate-300">{JSON.stringify(result??last??{},null,2)}</pre></div><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 className="mb-2 font-semibold">Recent errors / raw status</h2><pre className="max-h-96 overflow-auto text-xs text-slate-300">{JSON.stringify(status,null,2)}</pre></div></section></main>}
