export const dynamic = 'force-dynamic';

import Link from 'next/link';
import { buildCoverage, getTerritoryData, missingItems } from '@/lib/coverage';

function Card({ label, value, sub }: { label: string; value: number | string; sub?: string }) { return <div className="rounded-2xl border border-slate-800 bg-gradient-to-br from-slate-900 to-slate-950 p-5 shadow-xl shadow-slate-950/30"><div className="text-3xl font-bold text-slate-50">{value}</div><div className="mt-1 text-sm font-medium text-slate-300">{label}</div>{sub ? <div className="mt-1 text-xs text-slate-500">{sub}</div> : null}</div>; }
function Bar({ label, value, max }: { label: string; value: number; max: number }) { return <div><div className="mb-1 flex justify-between text-sm"><span>{label}</span><span className="text-slate-400">{value}</span></div><div className="h-2 rounded-full bg-slate-800"><div className="h-2 rounded-full bg-sky-400" style={{ width: `${max ? (value / max) * 100 : 0}%` }} /></div></div>; }

export default async function Home() {
  const { schools, districts, contacts, queue, runs } = await getTerritoryData();
  const coverage = buildCoverage(schools, contacts);
  const q = (s: string) => queue.filter((x) => x.status === s).length;
  const withWebsite = schools.filter((s) => s.website).length;
  const missing = (name: string) => schools.filter((s) => missingItems(s, contacts).includes(name)).length;
  const counties = [...schools.reduce((m, s) => m.set(s.county ?? 'Unknown', (m.get(s.county ?? 'Unknown') ?? 0) + 1), new Map<string, number>())].sort((a,b)=>b[1]-a[1]);
  const needs = schools.map((s) => ({ s, miss: missingItems(s, contacts) })).filter((x) => x.miss.length).sort((a,b)=>b.miss.length-a.miss.length).slice(0,12);
  const completeDistricts = coverage.filter((d) => d.missingCount === 0).length;
  const expectedSchools = coverage.reduce((n,d)=>n+d.expectedCount,0), foundExpected = coverage.reduce((n,d)=>n+d.foundCount,0);
  const lastRun = runs[0];

  const schoolsNeedingContactDiscovery = schools.filter((s)=>!contacts.some((c)=>c.school_id===s.id)).length;
  const lastMeaningful = runs.find((r)=>Number(r.rows_inserted ?? 0) || Number(r.rows_updated ?? 0) || Number(r.contacts_found ?? 0));

  return <main className="mx-auto max-w-7xl space-y-8 p-4 sm:p-6"><section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm uppercase tracking-[.25em] text-sky-300">Recruiter workbench</p><h1 className="mt-2 text-4xl font-bold text-slate-100">Lincoln Tech territory dashboard</h1><p className="mt-2 max-w-3xl text-slate-400">Baseline school and district coverage is complete. Contact and enrichment coverage is not complete, so the next useful work is phone, website, principal, counselor, and CTE/shop discovery plus manual review.</p></div><Link href="/coverage" className="min-h-11 rounded-xl bg-sky-400 px-4 py-3 font-semibold text-slate-950">Review Districts & Schools</Link></div></section>
  <section className="rounded-2xl border border-emerald-800/60 bg-emerald-950/25 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-semibold text-emerald-100">Baseline Coverage Complete</h2><p className="mt-1 text-sm text-emerald-200/80">Complete baseline roster: {coverage.length} of {coverage.length} expected districts and {foundExpected} of {expectedSchools} expected schools found.</p></div><div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><Card label="Expected districts" value={coverage.length}/><Card label="Found districts" value={completeDistricts}/><Card label="Expected schools" value={expectedSchools}/><Card label="Found schools" value={foundExpected}/></div></div></section>
  <section><h2 className="mb-3 text-xl font-semibold">Action gaps</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[
    ['Schools missing phone', missing('phone'), 'Needs phone/website'], ['Schools missing website', schools.length-withWebsite, 'Needs phone/website'], ['Schools missing principal', missing('principal'), 'Needs contact discovery'], ['Schools missing counselor', missing('counselor'), 'Needs contact discovery'], ['Schools missing CTE/shop contact', missing('CTE/shop contact'), 'Needs CTE/shop contact'], ['Contacts found', contacts.length, contacts.length ? 'Ready for outreach' : 'Needs contact discovery'], ['Crawl queue pending', q('pending'), 'Needs manual review'], ['Crawl queue failed', q('failed'), 'Needs manual review']
  ].map(([label,value,sub]) => <Card key={label} label={String(label)} value={value as number} sub={String(sub)} />)}</div></section>
  <section className="grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Crawl status</h2><div className="mt-3 space-y-2 text-sm text-slate-300"><p>Pending queue: {q('pending')}</p><p>Completed queue: {q('complete')}</p><p>Failed queue: {q('failed')}</p></div></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Last crawl activity</h2><p className="mt-3 text-sm text-slate-300">{lastRun ? `${lastRun.run_type} · ${lastRun.status} · ${lastRun.started_at}` : 'No discovery run recorded yet.'}</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Last meaningful update</h2><p className="mt-3 text-sm text-slate-300">{lastMeaningful ? `${lastMeaningful.run_type} · inserted ${lastMeaningful.rows_inserted ?? 0} · updated ${lastMeaningful.rows_updated ?? 0}` : 'No inserted or updated rows recorded yet.'}</p></div></section>
  <section className="rounded-2xl border border-sky-800/70 bg-slate-900 p-6 shadow-xl shadow-slate-950/30"><h2 className="text-2xl font-semibold">Territory Coverage Review</h2><p className="mt-2 max-w-4xl text-slate-300">Review every expected district and school in the recruiting territory. Use this to confirm which schools are already in the system, which data fields are missing, and what still needs contact discovery.</p><Link href="/coverage" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-sky-400 px-4 font-semibold text-slate-950">Review Districts & Schools</Link><ul className="mt-4 grid gap-2 text-sm text-slate-300 sm:grid-cols-3"><li>{coverage.length} of {coverage.length} expected districts found</li><li>{foundExpected} of {expectedSchools} expected schools found</li><li>{schoolsNeedingContactDiscovery} schools still need contact discovery</li></ul></section>
  <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-semibold">Needs attention</h2><div className="mt-4 overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead className="text-slate-400"><tr><th className="p-2 text-left">School</th><th className="p-2 text-left">District</th><th className="p-2 text-left">County</th><th className="p-2 text-left">Missing items</th><th className="p-2 text-left">Recommended next action</th></tr></thead><tbody>{needs.map(({s,miss})=><tr key={s.id} className="border-t border-slate-800"><td className="p-2">{s.name}</td><td className="p-2">{s.districts?.name ?? ''}</td><td className="p-2">{s.county}</td><td className="p-2 text-amber-200">{miss.join(', ')}</td><td className="p-2 text-slate-300">{miss.includes('phone') || miss.includes('website') ? 'Needs phone/website discovery.' : miss.includes('CTE/shop contact') ? 'Needs CTE/shop contact discovery.' : 'Needs manual review.'}</td></tr>)}</tbody></table></div></section></main>;
}
