export const dynamic = 'force-dynamic';
import Link from 'next/link';
import HelpIcon from '@/components/HelpIcon';
import { getTerritoryData, missingItems, recruitingProgress, schoolFlags } from '@/lib/coverage';
function pct(v:number,m:number){return Math.round(m? v/m*100:0)}
function Card({children}:{children:React.ReactNode}){return <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5 shadow-xl shadow-slate-950/20">{children}</section>}
function Progress({label,value,max,explain}:{label:string;value:number;max:number;explain:string}){return <div><div className="mb-1 flex flex-wrap justify-between gap-2 text-sm"><b>{label}</b><span className="text-sky-200">{pct(value,max)}% · {value} / {max}</span></div><div className="h-3 rounded-full bg-slate-800"><div className="h-3 rounded-full bg-gradient-to-r from-blue-900 via-sky-500 to-sky-300" style={{width:`${pct(value,max)}%`}} /></div><p className="mt-1 text-xs text-slate-400">{explain}</p></div>}
export default async function Home(){const {schools,contacts,aiUpdateRuns}=await getTerritoryData(); const progress=recruitingProgress(schools,contacts); const latest=aiUpdateRuns[0]; const latestIds=new Set((latest?.affected_record_ids??[]) as string[]); const latestSchools=schools.filter(s=>latestIds.has(s.id)).slice(0,8); const gaps=schools.map(s=>({s,miss:missingItems(s,contacts),flags:schoolFlags(s,contacts)})).filter(x=>x.miss.length).slice(0,10); const ready=schools.filter(s=>schoolFlags(s,contacts).ready);
return <main className="mx-auto max-w-7xl space-y-6 p-4 pb-24 sm:p-6"><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm uppercase tracking-[.25em] text-sky-300">Recruiting Data Progress <HelpIcon topic="Dashboard"/></p><h1 className="mt-2 text-4xl font-bold text-slate-100">How close is each school to being useful for outreach?</h1><p className="mt-2 max-w-3xl text-slate-400">AI Assisted Update is the primary way to add verified school data. Paste notes, school website text, or a ChatGPT-generated JSON update. Preview it, then commit verified changes to the CRM.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/json-import" className="min-h-11 rounded-xl bg-sky-400 px-4 py-3 font-semibold text-slate-950">Update school data with AI Assisted Update</Link><a href="/api/export" className="min-h-11 rounded-xl border border-slate-700 px-4 py-3">Export XLSX</a></div></section>
<Card><h2 className="text-2xl font-semibold">Progress Command Center</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{progress.cards.map(([l,v,m,e])=><Progress key={l} label={l} value={v} max={m} explain={e}/>)}</div></Card>
<section className="grid gap-4 lg:grid-cols-3"><Card><h2 className="text-xl font-semibold">Recently updated by AI Assisted Update</h2><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><dt className="text-slate-400">Latest run</dt><dd>{latest?.started_at??'none'}</dd><dt className="text-slate-400">Status</dt><dd>{latest?.status??'none'}</dd><dt className="text-slate-400">Schools updated</dt><dd>{latest?.updated_count??0}</dd><dt className="text-slate-400">Contacts created</dt><dd>{latest?.created_count??0}</dd><dt className="text-slate-400">Failed items</dt><dd>{latest?.failed_count??0}</dd></dl><div className="mt-4 flex flex-wrap gap-2"><Link href="/admin/json-import" className="rounded-lg border border-sky-700 px-3 py-2 text-sky-200">Open AI Assisted Update</Link><Link href="/coverage?filter=updated_recently" className="rounded-lg border border-slate-700 px-3 py-2">View latest import results</Link></div><ul className="mt-3 space-y-1 text-sm">{latestSchools.length?latestSchools.map(s=><li key={s.id}><Link className="text-sky-300 underline" href={`/schools/${s.id}`}>{s.name}</Link></li>):<li className="text-slate-400">No affected schools recorded yet.</li>}</ul></Card><Card><h2 className="text-xl font-semibold">Ready for outreach</h2><p className="mt-3 text-4xl font-bold text-emerald-200">{ready.length}</p><p className="text-sm text-slate-400">Schools with phone, website, address, and a useful contact or program note.</p></Card><Card><h2 className="text-xl font-semibold">Quick links</h2><div className="mt-3 grid gap-2 text-sm"><Link className="rounded-lg bg-slate-950 p-3 text-sky-200" href="/admin/json-import">Open AI Assisted Update</Link><Link className="rounded-lg bg-slate-950 p-3" href="/coverage">View schools updated in latest import</Link><a className="rounded-lg bg-slate-950 p-3 text-emerald-200" href="/api/export">Export XLSX</a></div></Card></section>
<Card><h2 className="text-2xl font-semibold">Top missing recruiting data</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{gaps.map(({s,miss})=><Link key={s.id} href={`/schools/${s.id}`} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><b>{s.name}</b><p className="text-sm text-amber-100">Missing: {miss.join(', ')}</p></Link>)}</div></Card></main>}
