import { TERRITORY_SCHOOL_SEEDS } from '@/data/territory-schools';
import { createServiceClient, hasSupabaseServiceCredentials } from './supabase';

export type DbRow = Record<string, any>;
const norm = (v: unknown) => String(v ?? '').trim().toLowerCase().replace(/&/g, ' and ').replace(/\b(sr|senior)\b/g, '').replace(/\bhigh school\b/g, 'high').replace(/[^a-z0-9]+/g, ' ').replace(/\s+/g, ' ').trim();
export const isPlaceholderDistrictName = (v: unknown) => typeof v === 'string' && v.startsWith('District To Verify -');
export const hasValue = (v: unknown) => v !== undefined && v !== null && String(v).trim().length > 0 && String(v).trim() !== '{}';
const isRecord = (v: unknown): v is Record<string, unknown> => typeof v === 'object' && v !== null && !Array.isArray(v);
export function hasMeaningfulGradeEnrollment(v: unknown) {
  if (!isRecord(v)) return false;
  return Object.values(v).some((value) => hasValue(value));
}
const role = (c: DbRow, words: string[]) => words.some((w) => norm(`${c.title} ${c.role_category} ${c.program_area} ${c.extraction_notes}`).includes(norm(w)));
const cteWords = ['cte','career','college and career','career technical','trades','trade','shop','automotive','welding','agriculture','ag','technical','workforce','counselor','diesel','construction','industrial','manufacturing'];
const schoolKey = (name: unknown, county: unknown, state: unknown) => `${norm(name)}|${norm(county)}|${norm(state)}`;
const districtKey = (name: unknown, county: unknown, state: unknown) => `${norm(name)}|${norm(county)}|${norm(state)}`;
const urlKey = (value: unknown) => { try { const url = new URL(String(value ?? '')); url.hash = ''; url.hostname = url.hostname.toLowerCase().replace(/^www\./, ''); url.pathname = url.pathname.replace(/\/+$/,'').replace(/\/index\.(html?|php)$/i, '') || '/'; return url.toString(); } catch { return String(value ?? '').trim(); } };

export function expectedDistricts() { const map = new Map<string, { district: string; county: string; state: string; expectedSchools: typeof TERRITORY_SCHOOL_SEEDS }>(); for (const s of TERRITORY_SCHOOL_SEEDS) { const key = districtKey(s.district_name, s.county, s.state); if (!map.has(key)) map.set(key, { district: s.district_name, county: s.county, state: s.state, expectedSchools: [] }); map.get(key)!.expectedSchools.push(s); } return [...map.values()].sort((a, b) => a.county.localeCompare(b.county) || a.district.localeCompare(b.district)); }

export async function getTerritoryData() {
  if (!hasSupabaseServiceCredentials()) return { schools: [] as DbRow[], districts: [] as DbRow[], contacts: [] as DbRow[], queue: [] as DbRow[], runs: [] as DbRow[], errors: [] as DbRow[], sources: [] as DbRow[], contactLogs: [] as DbRow[], tasks: [] as DbRow[], objectives: [] as DbRow[], jsonImports: [] as DbRow[], aiUpdateRuns: [] as DbRow[] };
  const db = createServiceClient();
  const [schools, districts, contacts, queue, runs, errors, sources, contactLogs, tasks, objectives, jsonImports, aiUpdateRuns] = await Promise.all([
    db.from('schools').select('*,districts(name,county,state)').limit(5000), db.from('districts').select('*').limit(1000), db.from('contacts').select('*').limit(10000), db.from('crawl_queue').select('*').limit(50000), db.from('discovery_runs').select('*').order('started_at', { ascending: false }).limit(20), db.from('crawl_errors').select('*').order('created_at', { ascending: false }).limit(500), db.from('source_urls').select('*').limit(5000), db.from('contact_logs').select('*').order('contacted_at', { ascending: false }).limit(5000), db.from('recruiting_tasks').select('*').order('created_at', { ascending: false }).limit(5000), db.from('dashboard_objectives').select('*').order('sort_order', { ascending: true }).limit(100), db.from('json_imports').select('*').order('created_at', { ascending: false }).limit(1000), db.from('ai_update_runs').select('*').order('started_at', { ascending: false }).limit(20),
  ]);
  for (const r of [schools, districts, contacts, queue, runs, errors, sources]) if (r.error) throw r.error;
  return { schools: schools.data ?? [], districts: districts.data ?? [], contacts: contacts.data ?? [], queue: queue.data ?? [], runs: runs.data ?? [], errors: errors.data ?? [], sources: sources.data ?? [], contactLogs: contactLogs.data ?? [], tasks: tasks.data ?? [], objectives: objectives.data ?? [], jsonImports: jsonImports.data ?? [], aiUpdateRuns: aiUpdateRuns.data ?? [] };
}

export function contactsForSchool(contacts: DbRow[], schoolId: string) { return contacts.filter((c) => c.school_id === schoolId); }
export function schoolFlags(s: DbRow | undefined, contacts: DbRow[]) { const schoolId = typeof s?.id === 'string' ? s.id : ''; const cs = schoolId ? contactsForSchool(contacts, schoolId) : []; const principal = cs.some((c) => role(c, ['principal'])); const counselor = cs.some((c) => role(c, ['counselor','career counselor','career_counselor','counseling','college career','college and career'])); const cte = hasValue(s?.special_programs) || hasValue(s?.program_notes) || hasValue(s?.cte_programs) || hasValue(s?.shop_programs) || hasValue(s?.trades_programs) || hasValue(s?.career_programs) || hasValue(s?.school_profile_notes) || cs.some((c) => role(c, cteWords)); const contact = principal || counselor || cs.length > 0; const enrollmentClue = hasValue(s?.student_population_total) || hasValue(s?.enrollment) || hasMeaningfulGradeEnrollment(s?.grade_enrollment); const lastAiUpdateAt = typeof s?.last_ai_update_at === 'string' ? s.last_ai_update_at : ''; return { exists: !!s, address: hasValue(s?.address), phone: hasValue(s?.phone), website: hasValue(s?.website), source: hasValue(s?.source_url), contacts: cs.length > 0, principal, counselor, cte, bell_schedule: hasValue(s?.bell_schedule) || hasValue(s?.bell_schedule_url), student_population: hasValue(s?.student_population_total) || hasValue(s?.enrollment), grade_enrollment: hasMeaningfulGradeEnrollment(s?.grade_enrollment), ready: hasValue(s?.phone) && (hasValue(s?.website) || hasValue(s?.address)) && (contact || cte || enrollmentClue || hasValue(s?.school_profile_notes) || hasValue(s?.program_notes)), needs_verification: s?.needs_verification === true || s?.verification_status === 'needs_verification' || (hasValue(s?.ai_created_at) && s?.verification_status !== 'complete' && s?.verification_status !== 'verified'), updated_recently: !!lastAiUpdateAt && Date.now() - new Date(lastAiUpdateAt).getTime() < 1000*60*60*24*14 }; }
export function missingItems(s: DbRow, contacts: DbRow[]) { const f = schoolFlags(s, contacts); const out: string[] = []; const districtName = isRecord(s.districts) ? s.districts.name : undefined; if (isPlaceholderDistrictName(districtName)) out.push('district'); if (!f.phone) out.push('phone'); if (!f.website) out.push('website'); if (!f.address) out.push('address'); if (!f.principal) out.push('principal'); if (!f.counselor) out.push('counselor'); if (!f.cte) out.push('CTE/shop info'); if (!f.bell_schedule) out.push('bell schedule'); if (!f.student_population) out.push('student population'); if (!f.grade_enrollment) out.push('grade enrollment'); return out; }
type SchoolFlags = ReturnType<typeof schoolFlags>;
type SchoolFlagKey = keyof SchoolFlags;
const progressDefinitions: Array<{ label: string; key: SchoolFlagKey; help: string }> = [
  { label: 'Schools with front desk phone', key: 'phone', help: 'schools.phone exists' },
  { label: 'Schools with website', key: 'website', help: 'schools.website exists' },
  { label: 'Schools with street address', key: 'address', help: 'schools.address exists' },
  { label: 'Schools with principal/contact info', key: 'principal', help: 'Linked contact title or role contains principal' },
  { label: 'Schools with counselor/contact info', key: 'counselor', help: 'Linked contact title or role contains counselor or career counselor' },
  { label: 'Schools with CTE/shop/program info', key: 'cte', help: 'Program/profile fields or linked CTE, trades, counselor, workforce, or career contact exists' },
  { label: 'Schools with bell schedule', key: 'bell_schedule', help: 'schools.bell_schedule or schools.bell_schedule_url exists' },
  { label: 'Schools with student population data', key: 'student_population', help: 'schools.student_population_total exists' },
  { label: 'Schools with grade-level enrollment breakdown', key: 'grade_enrollment', help: 'schools.grade_enrollment has grade-level values' },
  { label: 'Schools ready for recruiter outreach', key: 'ready', help: 'Phone plus website/address plus a useful contact, program note, or enrollment clue' },
  { label: 'Schools needing verification', key: 'needs_verification', help: 'needs_verification, verification_status, or AI-created records not marked complete' },
];
export function recruitingProgress(schools: DbRow[], contacts: DbRow[]) { const total = schools.length || 1; const count = (key: SchoolFlagKey) => schools.filter((s) => Boolean(schoolFlags(s, contacts)[key])).length; return { total, cards: progressDefinitions.map(({ label, key, help }): [string, number, number, string] => [label, count(key), total, help]) }; }

function buildSchoolMatcher(schools: DbRow[]) { const byKey = new Map<string, DbRow>(); const bySource = new Map<string, DbRow>(); const byNces = new Map<string, DbRow>(); for (const s of schools) { byKey.set(schoolKey(s.name, s.county, s.state), s); if (s.source_url) bySource.set(urlKey(s.source_url), s); if (s.nces_id) byNces.set(String(s.nces_id).trim(), s); } return (e: (typeof TERRITORY_SCHOOL_SEEDS)[number]) => byNces.get(e.nces_id) || bySource.get(urlKey(e.source_url)) || byKey.get(schoolKey(e.school_name, e.county, e.state)) || schools.find((s) => norm(s.name) === norm(e.school_name) && norm(s.county) === norm(e.county) && norm(s.state || e.state) === norm(e.state)) || schools.find((s) => norm(s.name).includes(norm(e.school_name)) && norm(s.county) === norm(e.county)); }
export function buildCoverage(schools: DbRow[], contacts: DbRow[]) { const match = buildSchoolMatcher(schools); return expectedDistricts().map((d) => { const foundSchools = d.expectedSchools.map((e) => ({ expected: e, found: match(e) })); const foundCount = foundSchools.filter((x) => x.found).length; const missingContacts = foundSchools.filter((x) => x.found && !schoolFlags(x.found, contacts).contacts).length; const needsVerification = foundSchools.filter((x) => x.found && x.found.verification_status !== 'verified').length; const status = foundCount === 0 ? 'Missing all schools' : foundCount === d.expectedSchools.length && missingContacts === 0 && needsVerification === 0 ? 'Complete' : foundCount === d.expectedSchools.length ? 'Needs recruiting data' : foundCount / d.expectedSchools.length >= .75 ? 'Mostly complete' : 'Missing some schools'; return { ...d, expectedCount: d.expectedSchools.length, foundCount, missingCount: d.expectedSchools.length - foundCount, missingContacts, needsVerification, status, schools: foundSchools }; }); }
