import { buildCoverage, DbRow, missingItems } from './coverage';
export const defaultObjectives = [
 ['Confirm baseline territory roster','Make sure expected districts and schools are in the CRM.','coverage'],['Find phone and website for every school','Fill phone and website gaps so every school can be contacted.','data'],['Find principal/contact office for every school','Find a main administrative contact path for each school.','contacts'],['Find counselor or college/career contact','Find counseling or college/career contacts for outreach.','contacts'],['Find CTE/shop/trades contact','Find instructors or coordinators tied to trades programs.','contacts'],['Make first outreach to every school','Call or email each school at least once.','outreach'],['Schedule first school visits','Turn warm outreach into visit dates.','visits'],['Complete follow-up notes for every contacted school','Log outcomes and next steps after outreach.','followup']
].map(([title,description,objective_type],i)=>({title,description,objective_type,status:i===0?'active':'archived',progress_current:0,progress_target:1,recommended_next_action:i===0?'Review Districts & Schools, then mark baseline roster confirmed.':'Choose this when the prior mission is complete.',sort_order:i+1}));
const has=(v:any)=>String(v??'').trim().length>0;
const role=(c:DbRow, re:RegExp)=>re.test(`${c.title??''} ${c.program_area??''} ${c.extraction_notes??''}`.toLowerCase());
export function missionMetrics(schools:DbRow[], districts:DbRow[], contacts:DbRow[], logs:DbRow[]){ const total=schools.length||1; const coverage=buildCoverage(schools,contacts); const contacted=new Set([...(logs??[]).map(l=>l.school_id),...schools.filter(s=>s.relationship_status&&s.relationship_status!=='not_started').map(s=>s.id)].filter(Boolean)); const ready=schools.filter(s=>(has(s.phone)||has(s.website))&&contacts.some(c=>c.school_id===s.id)).length; const follow=schools.filter(s=>s.relationship_status==='needs_follow_up'||has(s.next_follow_up_at)).length; const completeDistricts=coverage.filter(d=>d.missingCount===0 && d.missingContacts===0).length; const bars=[['School roster coverage',coverage.reduce((n,d)=>n+d.foundCount,0),Math.max(coverage.reduce((n,d)=>n+d.expectedCount,0),1),'Expected schools confirmed in the CRM.'],['Phone coverage',schools.filter(s=>has(s.phone)).length,total,'Schools with a callable phone number.'],['Website coverage',schools.filter(s=>has(s.website)).length,total,'Schools with an official website.'],['Principal contact coverage',schools.filter(s=>contacts.some(c=>c.school_id===s.id&&role(c,/principal/))).length,total,'Schools with principal or office leadership path.'],['Counselor contact coverage',schools.filter(s=>contacts.some(c=>c.school_id===s.id&&role(c,/counselor|counseling|college|career/))).length,total,'Schools with counseling or career path.'],['CTE/shop contact coverage',schools.filter(s=>contacts.some(c=>c.school_id===s.id&&role(c,/cte|shop|trade|welding|auto|diesel|construction|manufacturing|robotics|machining|wood/))).length,total,'Schools with trades/CTE path.'],['Schools contacted',contacted.size,total,'Schools with a logged outreach or relationship status.'],['Schools needing follow-up',follow,total,'Schools marked for follow-up.'],['Schools ready for outreach',ready,total,'Phone or website plus at least one contact path.'],['Districts fully reviewed',completeDistricts,Math.max(districts.length,coverage.length,1),'Districts with roster and contact coverage reviewed.']]; return {bars, ready, contacted:contacted.size, follow, biggestGap: bars.slice(1,6).sort((a,b)=>(Number(a[1])/Number(a[2]))-(Number(b[1])/Number(b[2])))[0]}; }
export const defaultPlan=['Review the territory coverage page.','Run crawl batches until pending queue reaches 0 or stops producing useful updates.','Review schools missing phone numbers.','Review schools missing websites.','Call schools missing key contact paths.','Ask for principal, counselor, CTE/shop/trades contact.','Log the call result.','Set a follow-up date.','Mark the school contacted, warm, active, not interested, or needs follow-up.','Export an updated report for boss review.'];
export function nextActions(schools:DbRow[],contacts:DbRow[]){return schools.map(s=>({school:s.name,action:missingItems(s,contacts).includes('phone')?'Find or call for phone number':missingItems(s,contacts).includes('website')?'Find official website':missingItems(s,contacts).includes('CTE/shop contact')?'Ask for CTE/shop/trades contact':s.next_follow_up_at?'Complete scheduled follow-up':'Make first outreach',priority:s.recruiting_priority??'medium'})).slice(0,10)}
