import { NextResponse } from 'next/server';
import { utils, write } from 'xlsx';
import { buildCoverage, getTerritoryData, missingItems } from '@/lib/coverage';
import { defaultPlan, missionMetrics } from '@/lib/mission';
export const dynamic = 'force-dynamic';
export async function GET(){try{const {schools,districts,contacts,queue,errors,sources,contactLogs,tasks,objectives,jsonImports}=await getTerritoryData();const coverage=buildCoverage(schools,contacts);const metrics=missionMetrics(schools,districts,contacts,contactLogs);const wb=utils.book_new();const add=(name:string,rows:Record<string,unknown>[])=>utils.book_append_sheet(wb,utils.json_to_sheet(rows.length?rows:[{}]),name.slice(0,31));
add('Boss Update Snapshot',[{territory_roster_status:coverage.every(d=>d.missingCount===0)?'complete':'needs review',schools_in_system:schools.length,districts_in_system:districts.length,contacts_found:contacts.length,schools_ready_for_outreach:metrics.ready,schools_contacted:metrics.contacted,schools_needing_follow_up:metrics.follow,biggest_remaining_gap:String(metrics.biggestGap[0]),summary:`Territory roster is ${coverage.every(d=>d.missingCount===0)?'complete':'still being confirmed'}. Main remaining gap: ${Number(metrics.biggestGap[2])-Number(metrics.biggestGap[1])} schools still need ${String(metrics.biggestGap[0]).toLowerCase()}.`}]);
add('Current Mission',(objectives.length?objectives:[{title:'Confirm baseline territory roster',status:'active'}]).map(o=>({title:o.title,description:o.description,status:o.status,progress_current:o.progress_current,progress_target:o.progress_target,recommended_next_action:o.recommended_next_action,completed_at:o.completed_at})));
add('Progress Summary',metrics.bars.map(([label,value,max,explanation])=>({label,value,max,percentage:Math.round(Number(value)/Number(max)*100),explanation})));
add('Plan of Action Tasks',(tasks.length?tasks:defaultPlan.map((title,i)=>({title,status:'not_started',priority:i<2?'high':'medium'}))).map(t=>({title:t.title,description:t.description,status:t.status,priority:t.priority,due_date:t.due_date,completed_at:t.completed_at,notes:t.notes})));
add('Schools',schools);add('Districts',districts);add('Contacts',contacts);add('Contact Logs',contactLogs??[]);
add('Missing Data',schools.map(s=>{const miss=missingItems(s,contacts);return {school:s.name,district:s.districts?.name,county:s.county,missing_website:miss.includes('website'),missing_phone:miss.includes('phone'),missing_principal:miss.includes('principal'),missing_counselor:miss.includes('counselor'),missing_cte_shop_contact:miss.includes('CTE/shop contact'),missing_source_url:miss.includes('source URL'),missing_items:miss.join(', '),relationship_status:s.relationship_status,next_follow_up_at:s.next_follow_up_at,recommended_next_action:miss.includes('phone')||miss.includes('website')?'Discover or manually enter phone/website':miss.includes('CTE/shop contact')?'Discover CTE/shop contact':miss.includes('principal')||miss.includes('counselor')?'Discover school contacts':'Manual review'}}).filter(r=>r.missing_items));
add('Coverage Summary',[{expected_districts:coverage.length,expected_schools:coverage.reduce((n,d)=>n+d.expectedCount,0),found_expected_schools:coverage.reduce((n,d)=>n+d.foundCount,0),missing_expected_schools:coverage.reduce((n,d)=>n+d.missingCount,0),schools_in_database:schools.length,contacts_in_database:contacts.length,pending_queue:queue.filter(q=>q.status==='pending').length,failed_queue:queue.filter(q=>q.status==='failed').length}]);
add('Program Gaps',schools.map(s=>({school:s.name,automotive:'',welding:'',diesel:'',cna:'',construction:'',manufacturing:'',engineering:'',robotics:'',machining:'',woodworking:'',industrial_technology:'',special_programs:s.special_programs,program_notes:s.program_notes})));
add('Source URLs',sources);add('Crawl Queue',queue);add('Crawl Errors',errors);add('JSON Imports',jsonImports??[]);
const buf=write(wb,{type:'buffer',bookType:'xlsx'});return new Response(buf,{headers:{'content-type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','content-disposition':'attachment; filename="lincoln-tech-territory.xlsx"'}})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Missing Supabase service credentials'},{status:500})}}
