'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import HelpIcon from '@/components/HelpIcon';
import { cleanExampleJson, schemaExample, supportedItemTypes } from '@/lib/json-import';

const prompt = `Use the information below to create a JSON update for the Lincoln Tech Territory CRM. Only include facts that are explicitly present in the pasted text. Do not invent names, emails, phone numbers, titles, dates, programs, or contacts. If a contact is missing, create a task saying what still needs to be found. Use item types supported by the CRM: school_update, district_update, contact_create, school_note_create, task_create, contact_log_create. Return only valid JSON. No markdown. No explanation.`;
const examples = [
  ['School homepage', 'Use this school homepage text to create school_update, district_update, school_note_create, and task_create items for missing follow-up.'],
  ['Staff directory', 'Extract only verified principals, counselors, career advisors, CTE/shop/trades contacts as contact_create items. Do not invent missing emails.'],
  ['Counselor page', 'Create contact_create items for counseling/career staff and tasks for any missing contact emails.'],
  ['CTE/shop page', 'Extract CTE, shop, automotive, welding, diesel, construction, agriculture, and trades contacts and program notes.'],
  ['Phone call note', 'Create contact_log_create, school_note_create, and task_create items from this call transcript.'],
  ['Feature request', 'Create a feature_request_create item describing this improvement for Aaron.'],
];
const tone: Record<string,string> = { applied:'border-emerald-700 bg-emerald-950/30', updated:'border-sky-700 bg-sky-950/30', created:'border-emerald-700 bg-emerald-950/30', warnings:'border-amber-700 bg-amber-950/30', failed:'border-red-700 bg-red-950/30', skipped:'border-slate-700 bg-slate-800/50', unchanged:'border-slate-700 bg-slate-800/50' };
function parseError(text: string, err: unknown) { const msg = err instanceof Error ? err.message : 'Invalid JSON'; const m = msg.match(/position (\d+)/); const pos = m ? Number(m[1]) : 0; const before = text.slice(0, pos); const line = before.split('\n').length; const column = before.length - before.lastIndexOf('\n'); const nearby = text.slice(Math.max(0,pos-90), pos+90); return { msg, line, column, nearby }; }
function FieldList({ item }: { item: any }) { const fields = [...(item.fields_changed ?? []), ...(item.fields_skipped ?? [])]; return fields.length ? <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-300">{fields.map((f:any,i:number)=><li key={i}><b>{f.label ?? f.field}:</b> {f.from !== undefined ? <>{String(f.from)} → </> : null}{f.to !== undefined ? String(f.to) : ''}{f.reason ? <span className="text-amber-200"> — {f.reason}</span> : null}</li>)}</ul> : null; }
function Card({ title, item, group }: { title: string; item: any; group: string }) { return <div className={`rounded-xl border p-4 ${tone[group] ?? tone.skipped}`}><h3 className="font-semibold">{title}</h3><div className="mt-2 space-y-1 text-sm text-slate-300"><p><b>Type:</b> {item.type}</p>{item.school ? <p><b>School:</b> {item.school}</p> : null}{item.district ? <p><b>District:</b> {item.district}</p> : null}{item.target_name ? <p><b>Target:</b> {item.target_name}</p> : null}{item.reason ? <p className="text-amber-100"><b>Note:</b> {item.reason}</p> : null}{item.suggested_fix ? <p className="text-sky-100"><b>Suggested fix:</b> {item.suggested_fix}</p> : null}{item.database_error ? <details className="rounded border border-red-900 bg-slate-950 p-2"><summary className="cursor-pointer text-red-100">Database error</summary><pre className="mt-2 whitespace-pre-wrap text-xs">{JSON.stringify(item.database_error, null, 2)}</pre></details> : null}{item.message ? <p>{item.message}</p> : null}{item.source_url ? <p><b>Source:</b> <a href={item.source_url} className="text-sky-300 underline" target="_blank">{item.source_url}</a></p> : null}</div><FieldList item={item}/></div>; }
function HumanSummary({ data, result=false }: { data:any; result?:boolean }) { if(!data) return <p className="text-sm text-slate-400">Validate an update to see a recruiter-friendly preview here.</p>; const groups = result ? ['updated','created','skipped','unchanged','warnings','failed'] : ['updated','created','warnings','failed','skipped','unchanged']; return <div className="space-y-4"><h2 className="text-2xl font-bold">{result ? 'Import Complete' : 'Preview changes before import'}</h2>{groups.map(g => data[g]?.length ? <section key={g}><h3 className="mb-2 font-semibold capitalize text-slate-100">{g} ({data[g].length})</h3><div className="grid gap-3 md:grid-cols-2">{data[g].map((item:any,i:number)=><Card key={`${g}-${i}`} title={titleFor(item, result)} item={item} group={g}/>)}</div></section> : null)}{result && missing(data).length ? <section className="rounded-xl border border-amber-700 bg-amber-950/30 p-4"><h3 className="font-semibold text-amber-100">Still missing</h3><ul className="mt-2 list-disc pl-5 text-sm text-amber-50">{missing(data).map(x=><li key={x}>{x}</li>)}</ul></section> : null}</div>; }
function titleFor(item:any, result:boolean) { const t=String(item.type).replaceAll('_',' '); if(item.type==='school_update') return result ? `Updated school: ${item.school ?? item.target_name}` : `School Update Preview: ${item.school ?? item.target_name}`; if(item.type==='district_update') return result ? `Updated district: ${item.district ?? item.target_name}` : `District Update Preview: ${item.district ?? item.target_name}`; if(item.type==='school_note_create') return result ? `Added note: ${item.school ?? ''}` : 'School Note Preview'; if(item.type==='task_create') return result ? `Added task: ${item.target_name ?? ''}` : 'Task Preview'; if(item.type?.startsWith('contact')) return result ? `Contact result: ${item.target_name ?? ''}` : 'Contact Preview'; return t; }
function missing(data:any){ const s=JSON.stringify(data).toLowerCase(); return ['Principal contact','Counselor contact','CTE/shop contact','Contact emails'].filter(x=>s.includes(x.toLowerCase().split(' ')[0]) || (x==='Contact emails' && s.includes('email is missing'))); }

export default function JsonImportPage() {
  const [text, setText] = useState(JSON.stringify(schemaExample, null, 2)); const [preview, setPreview] = useState<any>(null); const [result, setResult] = useState<any>(null); const [error, setError] = useState<any>(null); const valid = !!preview?.valid;
  const openSchoolId = useMemo(() => result?.updated?.find((x:any)=>x.type==='school_update' && x.record_id)?.record_id, [result]);
  async function call(url: string) { setError(null); if(url.includes('validate')) setResult(null); try { const json = JSON.parse(text); const response = await fetch(url, { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify(json) }); const body = await response.json(); if(!response.ok) { if (body?.failed || body?.skipped || body?.warnings) { url.includes('validate') ? setPreview(body) : setResult(body); return; } throw new Error(body.error ?? body.failed?.[0]?.reason ?? 'Request failed'); } url.includes('validate') ? setPreview(body) : setResult(body); } catch (err) { setError(err instanceof SyntaxError ? parseError(text, err) : { msg: err instanceof Error ? err.message : 'Invalid update format' }); } }
  const copyResult = () => navigator.clipboard.writeText(JSON.stringify(result ?? preview ?? {}, null, 2));
  const downloadResult = () => { const blob=new Blob([JSON.stringify(result ?? preview ?? {}, null, 2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='ai-assisted-import-result.json'; a.click(); URL.revokeObjectURL(a.href); };
  return <main className="mx-auto max-w-6xl space-y-6 p-4 pb-24 sm:p-6"><div><p className="text-sm uppercase tracking-[.25em] text-sky-300">Admin workflow</p><h1 className="mt-2 text-3xl font-bold">AI Assisted Update <HelpIcon topic="What is AI Assisted Update?"/></h1><p className="mt-2 text-slate-400">Paste ChatGPT JSON, preview human-readable changes, then import only what looks right.</p></div>
    <section className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-semibold">Supported item types</h2><ul className="mt-3 space-y-2 text-sm text-slate-300">{supportedItemTypes.map(t=><li key={t.type}><b>{t.type}</b> — {t.label}{!t.importable ? <span className="text-amber-200"> (recognized but not importable yet)</span> : null}</li>)}</ul></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-semibold">Safety rules</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-slate-300"><li>Existing values are preserved unless overwrite is true.</li><li>Contacts can be added without email, but emails must not be invented.</li><li>Duplicate notes and open tasks are skipped.</li><li>Raw JSON stays available under Technical details.</li></ul></div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-semibold">Copyable ChatGPT prompt</h2><button onClick={() => navigator.clipboard.writeText(`${prompt}\n\nExample JSON:\n${JSON.stringify(cleanExampleJson, null, 2)}`)} className="min-h-11 rounded-xl bg-sky-400 px-4 font-semibold text-slate-950">Copy Prompt</button></div><pre className="mt-3 whitespace-pre-wrap rounded-xl bg-slate-950 p-4 text-sm text-slate-200">{prompt}</pre><div className="mt-4 grid gap-3 md:grid-cols-3">{examples.map(([name, ex])=><div key={name} className="rounded-xl border border-slate-800 bg-slate-950 p-4"><p className="font-semibold text-sky-200">{name}</p><p className="mt-2 text-sm text-slate-300">{ex}</p><button onClick={()=>navigator.clipboard.writeText(`${prompt}\n\n${ex}\n\nPaste source text below:`)} className="mt-3 min-h-11 rounded-xl border border-slate-700 px-4 text-sm">Copy Example</button></div>)}</div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-semibold">Paste JSON update here</h2><textarea value={text} onChange={e=>{setText(e.target.value); setPreview(null);}} className="mt-3 min-h-[300px] w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-sm"/><div className="mt-3 flex flex-wrap gap-3"><button onClick={()=>call('/api/admin/json-import/validate')} className="min-h-11 rounded-xl border border-slate-700 px-4">Validate and Preview</button><button onClick={()=>call('/api/admin/json-import/apply')} disabled={!valid} className="min-h-11 rounded-xl bg-emerald-400 px-4 font-semibold text-slate-950 disabled:opacity-50">Import Previewed Update</button><button onClick={()=>navigator.clipboard.writeText(JSON.stringify(cleanExampleJson,null,2))} className="min-h-11 rounded-xl border border-slate-700 px-4">Copy clean example JSON</button></div>{error ? <div className="mt-3 rounded-xl border border-red-800 bg-red-950 p-4 text-red-100"><p className="font-semibold">Import problem: {error.msg}</p>{error.line ? <p className="mt-1 text-sm">Line {error.line}, column {error.column}</p> : null}{error.nearby ? <pre className="mt-2 whitespace-pre-wrap rounded bg-slate-950 p-3 text-xs">{error.nearby}</pre> : null}<ul className="mt-3 list-disc pl-5 text-sm"><li>Remove trailing commas.</li><li>Paste only from opening {'{'} to closing {'}'}.</li><li>Use double quotes, not smart quotes.</li><li>Do not paste markdown code fences.</li></ul></div> : null}</section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><HumanSummary data={preview}/><details className="mt-4 rounded-xl border border-slate-800 bg-slate-950 p-4"><summary className="cursor-pointer font-semibold">Technical details</summary><pre className="mt-3 max-h-96 overflow-auto text-xs text-slate-300">{JSON.stringify(preview, null, 2)}</pre></details></section>
    {result ? <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="mb-4 flex flex-wrap gap-3"><button onClick={copyResult} className="min-h-11 rounded-xl border border-slate-700 px-4">Copy import result</button><button onClick={downloadResult} className="min-h-11 rounded-xl border border-slate-700 px-4">Download import result</button>{openSchoolId ? <Link href={`/schools/${openSchoolId}`} className="grid min-h-11 place-items-center rounded-xl bg-sky-400 px-4 font-semibold text-slate-950">Open updated school</Link> : null}</div><HumanSummary data={result} result/><details className="mt-4 rounded-xl border border-slate-800 bg-slate-950 p-4"><summary className="cursor-pointer font-semibold">Technical details</summary><pre className="mt-3 max-h-96 overflow-auto text-xs text-slate-300">{JSON.stringify(result, null, 2)}</pre></details></section> : null}
  </main>;
}
