import { NextRequest, NextResponse } from 'next/server';
import { requireAdmin } from '@/lib/admin-auth';
import { normalizeImport } from '@/lib/json-import';
import { createServiceClient } from '@/lib/supabase';
const allowedSchool=['phone','website','recruiting_priority','relationship_status','last_contacted_at','next_follow_up_at','outreach_notes','latitude','longitude','location_accuracy','geocoded_at','geocoding_source','enrollment','mascot','graduation_date','bell_schedule_url','fafsa_or_career_event_notes','best_time_to_visit_seniors','special_programs','program_notes'];
function clean(it:any, keys:string[], existing:any={}){const out:any={}; for(const k of keys) if(it[k]!==undefined && it[k]!=='' && (it.overwrite || !existing?.[k])) out[k]=it[k]; return out;}
export async function POST(req:NextRequest){const admin=await requireAdmin(req); if('error'in admin)return NextResponse.json({error:admin.error},{status:admin.status}); const raw=await req.json(); const items=normalizeImport(raw); const db=createServiceClient(); const applied:any[]=[]; for(const it of items as any[]){let school:any=null; if(it.school_id){const r=await db.from('schools').select('*').eq('id',it.school_id).maybeSingle(); school=r.data}else if(it.school_name){const r=await db.from('schools').select('*').ilike('name',it.school_name).maybeSingle(); school=r.data} if(it.type==='school_update'&&school){await db.from('schools').update(clean(it,allowedSchool,school)).eq('id',school.id); applied.push({type:it.type,school:school.name});}
 if(it.type==='task_create'||it.type==='follow_up_create'){await db.from('recruiting_tasks').insert({title:it.title??it.notes??'Imported follow-up task',description:it.description,task_scope:school?'school':'global',school_id:school?.id,status:it.status??'not_started',priority:it.priority??'medium',due_date:it.due_date,created_by_email:admin.email,notes:it.notes}); if(it.type==='follow_up_create'&&school&&it.due_date) await db.from('schools').update({next_follow_up_at:it.due_date,relationship_status:'needs_follow_up'}).eq('id',school.id); applied.push({type:it.type});}
 if(it.type==='contact_log_create'&&school){await db.from('contact_logs').insert({school_id:school.id,district_id:school.district_id,contacted_by_email:admin.email,contact_method:it.contact_method??'other',outcome:it.outcome??'other',notes:it.notes,contacted_at:it.contacted_at??new Date().toISOString()}); applied.push({type:it.type,school:school.name});}
 if(it.type==='school_note_create'&&school){await db.from('recruiting_notes').insert({school_id:school.id,note:it.note??it.notes,source:'manual_json_import'}); applied.push({type:it.type,school:school.name});}
 if(it.type==='contact_create'&&school&&(it.source_url||it.source_notes)){await db.from('contacts').insert({school_id:school.id,district_id:school.district_id,name:it.name,title:it.title,email:it.email,phone:it.phone,program_area:it.program_area,source_url:it.source_url,source_notes:it.source_notes,confidence_score:it.source_url?'low':'manual_low',extraction_notes:'manual_json_import',imported_by_email:admin.email,imported_at:new Date().toISOString()}); applied.push({type:it.type,name:it.name});}}
 await db.from('json_imports').insert({imported_by_email:admin.email,import_type:'manual_json_import',raw_json:raw,summary:{applied},status:'imported'}); return NextResponse.json({ok:true,applied});}
